version: '3'
services:
  db:
    build:
      context: ./Database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - Language-Detection
  backend:
    build:
      context: ./BackEnd
    ports:
      - "80:80"
    networks:
      - Language-Detection
  frontend:
    build:
      context: ./FrontEnd
    ports:
      - "8501:8501"
    links:
      - db
    environment:
      PGHOST: db
    networks:
      - Language-Detection
    depends_on:
      - db
      - backend

networks:
  Language-Detection:
    driver: bridge
